export var term_html =
{
    en_html: `
    <div>
        <div class="faqans">
            <p>The <b style="font-family: OpenSans-Bold">“MPLE”</b> Reward Scheme (the «<b style="font-family: OpenSans-Bold">Scheme</b>") shall be governed by the following Terms and Conditions (hereinafter referred to as the “<b style="font-family: OpenSans-Bold">Terms</b>"):</p>
            <p><strong style="font-family: OpenSans-Bold"> 1. DEFINITIONS:</strong></p>
            <p>1.1. For the purposes of this Scheme, the following definitions shall apply:</p>
            <p><b style="font-family: OpenSans-Bold">«General Offer»</b> means the general offer approved by the Bank to be offered by Merchants, according to which the holders of Hellenic Bank’s Cards will collect cashback in the Wallet when carrying out transactions at the Merchants provided that they have downloaded and registered in the Mple Rewards App (mobile application).</p>
            <p><b style="font-family: OpenSans-Bold">«Basic Offer»</b> means the basic offer offered by the Merchant and which was approved by the Bank, according to which Hellenic Bank’s cardholders will collect cashback in their Wallet, when carrying out transactions at the Merchants, provided that they have downloaded and registered in the Mple Rewards App (mobile application).</p>
            <p><b style="font-family: OpenSans-Bold">«Special Offer»</b> means the special offer offered by the Merchant and which was approved by the Bank, according to which the holders of Hellenic Bank’s Cards will collect cashback, when carrying out transactions at the Merchants, in the Wallet or/and in the Card account, provided this transaction falls under the Special Offer’s terms and conditions and Cardholders have downloaded and registered in the Mple Rewards App (mobile application).</p>
            <p><b style="font-family: OpenSans-Bold">«Minimum Cashback Amount»</b> means the amount that must be collected in the Wallet in order for it to be redeemed, which is determined by the Cardholder and corresponds to any amount equal to or above €1.</p>
            <p><b style="font-family: OpenSans-Bold">«Merchant»</b> means the Merchants that concluded an agreement with Hellenic Bank Public Company Ltd in order to participate in the Scheme.</p>
            <p><b style="font-family: OpenSans-Bold">«Authorised Cardholder»</b> means a natural or legal person, other than the Main Cardholder to whom the Bank issues a Card at the instruction of the Main Cardholder and who is named therein and may use such Card.</p>
            <p><b style="font-family: OpenSans-Bold">«Card</b> means any debit, credit or prepaid card provided by the Bank.</p>
            <p><b style="font-family: OpenSans-Bold">«Main Cardholder»</b> means the person, natural or legal, on whose instructions a Card was issued (either in his name or in the name of an Authorized Cardholder) and to whose Account all Card transactions will be charged.</p>
            <p><b style="font-family: OpenSans-Bold">«Cardholders»</b> of the Scheme means the Main Cardholders and the Authorized Cardholders.</p>
            <p><b style="font-family: OpenSans-Bold">«Card Account»</b> means the Account maintained with the Bank in connection with transactions carried out by using a Card. The term includes, in the case of debit cards, the Current or Overdraft Account of the Cardholder, a Savings Account or a Notice Account which is charged with the Card transactions and in which such Card transactions are registered.</p>
            <p><b style="font-family: OpenSans-Bold">«Wallet»</b> means the virtual reward account for each Cardholder in which cashback is collected because of using a Card under the terms of this Agreement.</p>
            <p><b style="font-family: OpenSans-Bold">«Bank»</b> means Hellenic Bank Public Company Ltd.</p>
            <p><strong style="font-family: OpenSans-Bold">2. SCHEME:</strong></p>
            <p>2.1. The Scheme concerns collecting cashback in the Wallet through Card transactions carried out in a Merchant and the ability to use them in a Merchant as defined in these terms.</p>
            <p><strong style="font-family: OpenSans-Bold">3. COLLECTION OF CASHBACK:</strong></p>
            <p>3.1.	Every time a Cardholder uses a Card to carry out a transaction at a Merchant, either at a terminal used by the Merchant at its premises or online and provided the terminal is registered at the Merchant, cashback will be collected in his/her Wallet or/and Card Account, according to the contribution agreed between the Merchant and the Bank in relation to the General or/and Basic or/and Special Offer.</p>
            <p>3.2.	In case of a Special Offer offered by a Merchant, additional cashback will be collected in the Wallet or in the Card Account, provided that the Cardholder carries out a transaction that meets the terms of such Special Offer.</p>
            <p>3.3.	If the Cardholder carries out a transaction at a Merchant online and the Card payment is made directly at the Merchant through its website, but the sales carried out through the website of such Merchant are not explicitly included in the Scheme, then no cashback will be collected in the Wallet or/and in the Card Account.</p>
            <p>3.4.	If the Cardholder carries out a transaction at a Merchant online by using a disposable virtual Card, then no cashback will be collected in the Wallet or/and in the Card Account.</p>
            <p>3.5.	Cashback will be collected once the transaction at a Merchant is approved by the Bank's system. </p>
            <p><strong style="font-family: OpenSans-Bold">4. CASHBACK:</strong></p>
            <p>4.1.	Cashback which have been collected in the Wallet, will be refunded to the Card Account, provided that the Cardholder activates the option “Cashback Preferences” in the Mple Rewards App (mobile application), selects the Card Account to which cashback will be refunded from the Wallet and subject to clause 4.3.</p>
            <p>4.2.	Cashback can be affected directly to the Card Account in the case of an instant offer and such refund will be made after the Cardholder carries out the transaction.</p>
            <p>4.3. Subject to clause 4.1., Cashback will be affected shortly after the Cardholder carries out the transaction, provided that the cashback available in the Wallet exceeds the Minimum Cashback Amount for the total amount of the transaction or part thereof, if the transaction amount is greater than the amount of cashback collected. In case the cashback available in the Wallet exceeds the Minimum Cashback Amount for the total amount of the transaction or part thereof, if the transaction amount is greater than the amount of cashback collected, the full amount of cashback available in the Wallet will be used and not part thereof. It is provided that in cases where the amount of the transaction is less than the amount collected by the Cardholder, only the amount corresponding to the amount of the purchase will be refunded and the remaining amount of cashback will remain in the Wallet.</p>
            <p>4.4.	Provided that in case the Cardholder holds more than one Card, he/she reserves the right, at any time, to select a different card through the Mple Rewards App (mobile application) in relation to the Scheme from which the cashback available in the Wallet will be used.</p>
            <p>4.5.	If the use of the Card is suspended or the Card is cancelled for any reason, the Cardholder will not be able to use the cashback collected in his/her Wallet or/and Card Account by using the said Card or/and proceed with the filling of an application for the issuance of another Card. It is also understood that the Cardholder will be able to select another Card in order to use the cashback collected.</p>
            <p>4.6.	If the Card Account will be closed, the Wallet will no longer be available to the Cardholder and the cashback available in the Wallet will be deleted by the Bank.</p>
            <p><strong style="font-family: OpenSans-Bold">5. TERM OF VALIDITY OF THE CASHBACK:</strong></p>
            <p>5.1.	The cashback collected from General Offer shall be available for a term of 2 years from the date of their collection and the cashback collected from Basic Offer shall be available for a term of 1 year from the date of their collection. The period under which the cashback collected from Special Offer shall be available, will be governed by the terms and conditions of each Special Offer.Provided that upon the expiry of the cashback, any cashback that has not been used by the Cardholder, will be deleted.</p>
            <p>5.2.	Further, should any Merchant terminate its agreement with the Bank, then any Basic Offer shall be void. Any Special Offer offered by the Merchant prior to termination of the Agreement shall be void. It is provided that any cashback collected in the Wallet, which has not been used by the Cardholder prior to the termination of the agreement by the Merchant, cannot be used by the Cardholder and will be deducted from the Wallet.</p>
            <p><strong style="font-family: OpenSans-Bold">6. SPECIAL CONDITIONS:</strong></p>
            <p>6.1.	The Bank may modify, withdraw, suspend and/or terminate the Scheme or any part thereof, without notice and at any time, at its absolute discretion, unless any modification, withdrawal, suspension and/or termination is deemed necessary for reasons of force majeure. Reasons of force majeure will be deemed to be any reasons beyond the control of the Bank for the purposes of these Terms.</p>
            <p>6.2.	The Bank reserves the right to admit a new Merchant in the Scheme or to delete an existing Merchant from the Scheme without giving any notice to the Cardholder.</p>
            <p>6.3.	The Bank shall not be liable for any damaged or defective products or for the provision of unsatisfactory services by the Merchants.</p>
            <p>6.4.	Any disputes between a Merchant and the Cardholder with respect to any goods or services offered under the Scheme shall not in any way concern and/or affect the Bank.</p>
            <p>6.5.	The Bank shall not be liable if any Merchant refuses for any reason to accept the Cardholder's Card or if it withdraws from the Scheme.</p>
            <p>6.6.	Participation in the Scheme is considered as an irrevocable and unconditional acceptance of these Terms and the Terms of Use of the Bank’s Cards as these are posted on the Bank's website at <a href="https://www.hellenicbank.com">https://www.hellenicbank.com</a></p>
            <p>6.7.	These Terms and any amendments thereto shall be governed by Cyprus Law.</p>
        </div>
    </div>`,
    gr_html: `
    <div>
        <div class="faqans">
            <p>To Σχέδιο Επιβράβευσης <b style="font-family: OpenSans-Bold">“ΜΠΛΕ”</b> («<b style="font-family: OpenSans-Bold">Σχέδιο</b>») διέπεται από τους πιο κάτω όρους και προϋποθέσεις (στο εξής "<b style="font-family: OpenSans-Bold">Όροι</b>”):</p>
            <p><strong style="font-family: OpenSans-Bold"> 1. OΡΙΣΜΟΙ:</strong></p>
            <p>1.1. Για τους σκοπούς του παρόντος Σχεδίου, θα ισχύουν οι εξής ορισμοί: </p>
            <p><b style="font-family: OpenSans-Bold">«Γενική Προσφορά»</b> σημαίνει τη γενική προσφορά που έχει εγκριθεί από την Τράπεζα για να προσφέρουν οι Έμποροι, βάσει της οποίας, κατά την πραγματοποίηση συναλλαγών στους Εμπόρους , οι Κάτοχοι Καρτών, θα συλλέγουν χρήματα στο Πορτοφόλι νοουμένου ότι έχουν κάνει εγγραφή  μέσω της σχετικής εφαρμογής κινητού Mple Rewards (mobile application).</p>
            <p><b style="font-family: OpenSans-Bold">«Βασική Προσφορά»</b> σημαίνει τη βασική προσφορά που έχει εγκριθεί από την Τράπεζα για να προσφέρουν οι Έμποροι, βάσει της οποίας, κατά την πραγματοποίηση συναλλαγών στους Εμπόρους, οι Κάτοχοι Καρτών, θα συλλέγουν χρήματα στο Πορτοφόλι νοουμένου ότι έχουν κάνει εγγραφή  μέσω της σχετικής εφαρμογής κινητού Mple Rewards (mobile application).</p>
            <p><b style="font-family: OpenSans-Bold">«Ειδική Προσφορά»</b> σημαίνει την ειδική προσφορά που προσφέρει ο Έμπορος και έχει εγκριθεί από την Τράπεζα, βάσει της οποίας κατά την πραγματοποίηση συναλλαγών στους Εμπόρους, οι Κάτοχοι Καρτών θα συλλέγουν χρήματα στο Πορτοφόλι ή/και στον Λογαριασμό Κάρτας, νοουμένου ότι η συναλλαγή θα εμπίπτει στους όρους και προϋποθέσεις της εν λόγω Ειδικής Προσφοράς και ότι οι Κάτοχοι Κάρτας έχουν κάνει εγγραφή μέσω της σχετικής εφαρμογής κινητού Mple Rewards (mobile application).</p>
            <p><b style="font-family: OpenSans-Bold">«Ελάχιστο Ποσό Επιστροφής»</b> σημαίνει το ποσό που πρέπει να συλλεχθεί στο Πορτοφόλι  με σκοπό να μπορεί να πραγματοποιηθεί η εξαργύρωση αυτού, το οποίο καθορίζεται από τον Κάτοχο Κάρτας και αναλογεί σε οποιοδήποτε ποσό ίσο με ή άνω των €1.</p>
            <p><b style="font-family: OpenSans-Bold">«Έμπορος»</b> σημαίνει τους Εμπόρους που έχουν συνάψει συμφωνία με την Ελληνική Τράπεζα Δημόσια Εταιρεία Λτδ για να συμμετέχουν στο Σχέδιο.</p>
            <p><b style="font-family: OpenSans-Bold">«Εξουσιοδοτημένος Κάτοχος Κάρτας»</b> σημαίνει πρόσωπο, φυσικό ή νομικό, άλλο από τον Κυρίως Κάτοχο Κάρτας, στον οποίο η Τράπεζα εκδίδει Κάρτα κατ’ εντολή του Κυρίως Κατόχου Κάρτας και που κατ’ επέκταση κατονομάζεται σε και δύναται να χρησιμοποιεί τέτοια Κάρτα.</p>
            <p><b style="font-family: OpenSans-Bold">«Κάρτα»</b> σημαίνει οποιαδήποτε χρεωστική, πιστωτική ή προπληρωμένη κάρτα που παρέχεται από την Τράπεζα.</p>
            <p><b style="font-family: OpenSans-Bold">«Κύριος κάτοχος Κάρτας»</b> σημαίνει το πρόσωπο, φυσικό ή νομικό, κατ’ εντολή του οποίου έχει εκδοθεί Κάρτα (είτε στο όνομά του είτε σε Εξουσιοδοτημένο Κάτοχο Κάρτας) και στον Λογαριασμό του οποίου θα χρεώνονται όλες οι συναλλαγές με τέτοια/ες Κάρτα/ες.</p>
            <p><b style="font-family: OpenSans-Bold">«Κάτοχοι Κάρτας»</b> του Σχεδίου, σημαίνει οι Κύριοι Κάτοχοι Καρτών και οι Εξουσιοδοτημένοι Κάτοχοι Καρτών.</p>
            <p><b style="font-family: OpenSans-Bold">«Λογαριασμός Κάρτας»</b> σημαίνει τον Λογαριασμό που διατηρείται στην Τράπεζα σε σχέση με συναλλαγές με χρήση Κάρτας. Στην περίπτωση χρεωστικών καρτών, ο όρος περιλαμβάνει τρεχούμενο Λογαριασμό του Κατόχου Κάρτας, με ή χωρίς υπερανάληψη, Λογαριασμό ταμιευτηρίου ή Λογαριασμό Προειδοποίησης στον οποίο χρεώνονται και παρουσιάζονται οι συναλλαγές με Κάρτα.</p>
            <p><b style="font-family: OpenSans-Bold">«Πορτοφόλι»</b> σημαίνει τον εικονικό λογαριασμό επιβράβευσης για κάθε Κάτοχο Κάρτας στον οποίο συλλέγονται χρήματα λόγω της χρήσης Κάρτας δυνάμει των όρων της παρούσας Συμφωνίας.</p>
            <p><b style="font-family: OpenSans-Bold">«Τράπεζα»</b> σημαίνει την Ελληνική Τράπεζα Δημόσια Εταιρεία Λτδ.</p>
            <p><strong style="font-family: OpenSans-Bold">2. ΣΧΕΔΙΟ:</strong></p>
            <p>2.1.	Το Σχέδιο αφορά τη συλλογή χρημάτων στο Πορτοφόλι, από συναλλαγές με Κάρτα στον Έμπορο και στη δυνατότητα χρήσης αυτών στον Έμπορο, ως ορίζεται στους παρόντες όρους.</p>
            <p><strong style="font-family: OpenSans-Bold">3. ΣΥΛΛΟΓΗ ΜΕΤΡΗΤΩΝ:</strong></p>
            <p>3.1.	Κάθε φορά που Κάτοχος Κάρτας χρησιμοποιεί Κάρτα για να πραγματοποιήσει συναλλαγή σε Έμπορο, είτε σε τερματικό που χρησιμοποιεί ο Έμπορος στις εγκαταστάσεις του, είτε μέσω διαδικτύου και νοουμένου ότι το τερματικό είναι εγγεγραμμένο στον Έμπορο, θα συλλέγονται χρήματα στο Πορτοφόλι ή/και στον Λογαριασμό Κάρτας ανάλογα με το εκάστοτε ποσοστό που έχει συμφωνηθεί μεταξύ της Τράπεζας και του Εμπόρου σε σχέση με τη Γενική ή/και Βασική ή/και Ειδική Προσφορά.</p>
            <p>3.2.	Σε περίπτωση Ειδικής Προσφοράς, θα συλλέγονται χρήματα στο Πορτοφόλι ή/και στον Λογαριασμό Κάρτας, νοουμένου ότι ο Κάτοχος Κάρτας θα πραγματοποιήσει συναλλαγή που θα εμπίπτει στους όρους και προϋποθέσεις της εκάστοτε Ειδικής Προσφοράς.</p>
            <p>3.3.	Εάν ο Κάτοχος Κάρτας πραγματοποιήσει συναλλαγή σε Έμπορο  μέσω διαδικτύου και η πληρωμή με την Κάρτα διεξάγεται απευθείας με τον Έμπορο μέσω της ιστοσελίδας του, αλλά οι πωλήσεις μέσω της ιστοσελίδας του Εμπόρου δεν περιλαμβάνονται ρητά στο Σχέδιο, τότε δεν θα συλλέγονται χρήματα στο Πορτοφόλι ή/και στον Λογαριασμό Κάρτας.</p>
            <p>3.4.	Εάν ο Κάτοχος Κάρτας πραγματοποιήσει συναλλαγή σε Έμπορο, μέσω διαδικτύου με εικονική Κάρτα μίας χρήσης, τότε δεν θα συλλέγονται χρήματα στο Πορτοφόλι ή/και στον Λογαριασμό Κάρτας.</p>
            <p>3.5.	Η συλλογή χρημάτων θα γίνεται κατά την έγκριση της διεξαγωγής της συναλλαγής από το σύστημα της Τράπεζας.</p>
            <p><strong style="font-family: OpenSans-Bold">4. ΕΠΙΣΤΡΟΦΗ ΜΕΤΡΗΤΩΝ:</strong></p>
            <p>4.1.	Χρήματα, που έχουν συλλεχθεί στο Πορτοφόλι, θα επιστρέφονται στον Λογαριασμό Κάρτας, νοουμένου ότι ο Κάτοχος Κάρτας έχει ενεργοποιήσει την επιλογή «Ρυθμίσεις επιστροφής χρημάτων» μέσω της εφαρμογής κινητού Mple Rewards (mobile application) και έχει επιλέξει τον Λογαριασμό Κάρτας στον οποίο θα επιστρέφονται χρήματα από το Πορτοφόλι και τηρουμένων των όσων αναφέρονται στον όρο 4.3.</p>
            <p>4.2.	Επιστροφή χρημάτων μπορεί να γίνει απευθείας στον Λογαριασμό Κάρτας σε περίπτωση άμεσης προσφοράς (instant offer) και τέτοια επιστροφή πραγματοποιείται μετά τη διεξαγωγή της συναλλαγής από τον Κάτοχο Κάρτας.</p>
            <p>4.3.	Η επιστροφή χρημάτων τηρουμένων των όσων αναφέρονται στον όρο 4.1., πραγματοποιείται μετά τη διεξαγωγή της συναλλαγής από τον Κάτοχο Κάρτας, νοουμένου ότι τα χρήματα στο Πορτοφόλι που έχουν ήδη συλλεχθεί από τις Γενικές Προσφορές και τις Ειδικές Προσφορές του Εμπόρου στον οποίον πραγματοποιείται η συναλλαγή αλλά και το ποσό αυτής, υπερβαίνουν το Ελάχιστο Ποσό Επιστροφής. Νοείται ότι στις περιπτώσεις που το ποσό της συναλλαγής είναι μικρότερο του ποσού που έχει συλλέξει ο Κάτοχος Κάρτας, θα επιστρέφεται μόνο το ποσό που αντιστοιχεί στο ποσό της αγοράς και τα υπόλοιπα χρήματα θα παραμένουν στο Πορτοφόλι.</p>
            <p>4.4.	Νοείται ότι σε περίπτωση που Κάτοχος Κάρτας κατέχει περισσότερες από μία Κάρτες, διατηρεί το δικαίωμα, ανά πάσα στιγμή, να επιλέξει, μέσω της εφαρμογής κινητού Mple Rewards (mobile application), την Κάρτα μέσω της οποίας επιθυμεί να γίνεται η χρήση των χρημάτων που έχουν συλλεχθεί.</p>
            <p>4.5.	Σε περίπτωση αναστολής χρήσης ή ακύρωσης Κάρτας, για οποιοδήποτε λόγο, ο Κάτοχος Κάρτας δεν θα μπορεί να χρησιμοποιήσει τα χρήματα που έχουν συλλεχθεί στο Πορτοφόλι ή/και στον Λογαριασμό Κάρτας κάνοντας χρήση της Κάρτας που έχει ανασταλεί ή ακυρωθεί. Νοείται ότι ο Κάτοχος Κάρτας θα μπορεί να επιλέξει άλλη Κάρτα ή/και προβεί σε αίτηση για έκδοση άλλης Κάρτας για να χρησιμοποιήσει τα χρήματα που έχουν συλλεχθεί.</p>
            <p>4.6.	Σε περίπτωση κλεισίματος του Λογαριασμού Κάρτας, το Πορτοφόλι δεν θα είναι διαθέσιμο για χρήση προς τον Κάτοχο Κάρτας και τα χρήματα που έχουν συλλεχθεί σε αυτό θα διαγράφονται από την Τράπεζα.</p>
            <p><strong style="font-family: OpenSans-Bold">5. ΔΙΑΡΚΕΙΑ ΙΣΧΥΟΣ ΜΕΤΡΗΤΩΝ:</strong></p>
            <p>5.1.	Η διάρκεια ισχύος των χρημάτων που έχουν συλλεχθεί από Γενική Προσφορά θα είναι 2 χρόνια από την ημερομηνία συλλογής τους και η διάρκεια ισχύος των χρημάτων που έχουν συλλεχθεί από Βασική Προσφορά θα είναι 1 χρόνος από την ημερομηνία συλλογής τους. Η διάρκεια ισχύος των χρημάτων που έχουν συλλεχθεί από Ειδική Προσφορά θα διέπεται από τους όρους και προϋποθέσεις της εκάστοτε Ειδικής Προσφοράς. Νοείται ότι κατά την λήξη ισχύος των χρημάτων, οποιαδήποτε χρήματα που δεν έχουν χρησιμοποιηθεί από τον Κάτοχο Κάρτας, θα διαγράφονται.</p>
            <p>5.2.	Περαιτέρω, σε περίπτωση που ο οποιοσδήποτε Έμπορος τερματίσει τη συμφωνία που έχει συνάψει με την Τράπεζα, τότε θα ακυρώνεται η Βασική και/ή Ειδική Προσφορά. Οποιαδήποτε τυχόν Βασική και/ή Ειδική Προσφορά έχει προσφερθεί από τον Έμπορο, προ του τερματισμού της συμφωνίας, θα ακυρώνεται. Νοείται ότι οποιαδήποτε χρήματα έχουν συλλεχθεί στο Πορτοφόλι,  και δεν έχουν χρησιμοποιηθεί από τον Κάτοχο Κάρτας προ του τερματισμού της συμφωνίας από τον Έμπορο, δεν θα μπορούν να χρησιμοποιηθούν από τον Κάτοχο Κάρτας και θα αφαιρούνται από το Πορτοφόλι.</p>
            <p><strong style="font-family: OpenSans-Bold">6. ΕΙΔΙΚΟΙ ΟΡΟΙ:</strong></p>
            <p>6.1.	Η Τράπεζα δύναται να τροποποιεί, αποσύρει, αναστείλει ή/και διακόψει το Σχέδιο ή οποιοδήποτε μέρος αυτού, χωρίς ειδοποίηση και καθ’ οιονδήποτε χρόνο, κατά την απόλυτη κρίση της, εκτός εάν οποιαδήποτε τροποποίηση, απόσυρση, αναστολή ή/και διακοπή θεωρηθεί απαραίτητη για λόγους ανωτέρας βίας. Λόγοι ανωτέρας βίας θεωρούνται για τους σκοπούς των παρόντων Όρων οποιοιδήποτε λόγοι εκτός του ελέγχου της Τράπεζας.</p>
            <p>6.2.	Η Τράπεζα διατηρεί το δικαίωμα να εντάξει νέο Έμπορο ή να διαγράψει υφιστάμενο Έμπορο από το Σχέδιο χωρίς οποιαδήποτε προειδοποίηση του Κατόχου Κάρτας.</p>
            <p>6.3.	Η Τράπεζα δεν φέρει οποιαδήποτε ευθύνη για τυχόν κατεστραμμένα ή ελαττωματικά προϊόντα ή την προσφορά μη ικανοποιητικών υπηρεσιών από τους Εμπόρους.</p>
            <p>6.4.	Οποιεσδήποτε τυχόν διαφορές μεταξύ του Εμπόρου και του Κατόχου Κάρτας σε σχέση με οποιοδήποτε εμπόρευμα ή υπηρεσία προσφέρεται κάτω από το Σχέδιο δεν αφορούν και/ή δεν επηρεάζουν με οποιονδήποτε τρόπο την Τράπεζα.</p>
            <p>6.5.	Η Τράπεζα δεν φέρει οποιαδήποτε ευθύνη αν οποιοσδήποτε Έμπορος αρνηθεί για οποιοδήποτε λόγο να αποδεχθεί την Κάρτα του Κατόχου Κάρτας ή αν αποσυρθεί από το Σχέδιο.</p>
            <p>6.6.	Η συμμετοχή στο Σχέδιο θεωρείται ως αμετάκλητη και ανεπιφύλακτη αποδοχή των παρόντων Όρων και των Όρων Χρήσης Καρτών της Τράπεζας, όπως αυτοί αναρτώνται στην ιστοσελίδα της Τράπεζας <a href="https://www.hellenicbank.com">https://www.hellenicbank.com</a></p>
            <p>6.7.	Οι παρόντες Όροι και οποιεσδήποτε τροποποιήσεις αυτών θα διέπονται από το Κυπριακό Δίκαιο.</p>
        </div>
    </div>`
    }