export const config_path = {
    first_page: "FirstPage",
    landing_page: 'LandingPage',
    login: "Login",
    login_otp: "LoginWithOtp",
    register: "Register",
    home_page_router: "HomePageRouter",
    offers_router: "OffersRouter",
    merchants_router: "MerchantsRouter",
    spend_prefrences: "SpendPreferences",
    my_account_router: "MyAccountRouter",
    verify_email: "VerifyEmail",
    forgot_password: "ForgotPassword",
    verification : "Verification",
    home_drawer_router : "HomeDrawerRouter",
    profile: "Profile",
    contact_us: "ContactUs",
    about: "About",
    term_condition: "TermAndConditions",
    faq_router: "FAQRouter",
    profile_router: "ProfileRouter",
    notification_detail: "NotificationDetail",
    tab_bar_router: "TabBarRouter",
    faqs : "FAQs",
    faq_detail: "FAQDetail",
    profile_email: "ProfileEmail",
    home: "Home",
    allotment_detail: "AllotmentDetail",
    merchants: "Merchants",
    merchant_detail: "MerchantDetail",
    my_account: "MyAccount",
    my_cards: "MyCards",
    transactions: "Transactions",
    notifications: "Notifications",
    profile_setting: "ProfileSetting",
    offers: "Offers",
    offer_detail: "OfferDetail",
}